name: .NET

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./dotnet/hw1/hw1.sln
    - name: Build
      run: dotnet build --no-restore ./dotnet/hw1/hw1.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./dotnet/hw1/hw1.tests/hw1.tests.csproj
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: CoverResults.xml
